import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BOARD)

LED1 = 37
LED2 = 35
LED3 = 33
LED4 = 31
LED5 = 29

# Setup GPIO pins
GPIO.setup(LED1, GPIO.OUT)
GPIO.setup(LED2, GPIO.OUT)
GPIO.setup(LED3, GPIO.OUT)
GPIO.setup(LED4, GPIO.OUT)
GPIO.setup(LED5, GPIO.OUT)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 0)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 0)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 0)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 0)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 0)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.output(LED1, 1)
GPIO.output(LED2, 1)
GPIO.output(LED3, 1)
GPIO.output(LED4, 1)
GPIO.output(LED5, 1)
time.sleep(0.5)

GPIO.cleanup()

